BINSTORE_BASE defined externally; minor syntactic sugar

diff --git a/git-bin b/git-bin
--- a/git-bin
+++ b/git-bin
@@ -1,10 +1,18 @@
+BINSTORE_BASE=${BINSTORE_BASE:-}
+
+if [ -z "$BINSTORE_BASE" ];
+then
+    echo "git-bin: no BINSTORE_BASE set. Please set this in your environment before trying again."
+    exit 2
+fi
+
 remotename=`git remote -v | grep -E "origin.*push" | grep -oE "@([^ ]+)" | grep -oE "[:/][^ ]+" | cut -c 2-`
-BINSTORE=$(dirname /media/lab/gitserve/gitbin-store/$remotename/blah) #using dirname with a fake file to clean up double slashes etc.
+binstore=$(dirname $BINSTORE_BASE/$remotename/blah) #using dirname with a fake file to clean up double slashes etc.
 
 function addbin {
-    [[ -d $BINSTORE ]] || mkdir -p $BINSTORE
+    [[ -d $binstore ]] || mkdir -p $binstore
 
-    while [[ "x$1" != "x" ]];
+    while [[ ! -z "$1" ]];
     do
         src=$1 ; shift
         [[ "$(basename $src)" == "." ]] && continue
@@ -18,38 +26,38 @@ function addbin {
         hash=`md5sum $src | cut -d" " -f1`
         # check whether the file is already a symlink to its hash in the binstore
         # i.e. there is nothing to reset
-        [[ -L $src && "`readlink $src`" == "$BINSTORE/$hash" ]] && continue 
+        [[ -L $src && "`readlink $src`" == "$binstore/$hash" ]] && continue 
 
-        echo "git-bin-add: adding $src with hash $hash to $BINSTORE"
+        echo "git-bin-add: adding $src with hash $hash to $binstore"
 
-        if [[ -e $BINSTORE/$hash && `stat -c%s $BINSTORE/$hash` != `stat -c%s $src` ]]; then
+        if [[ -e $binstore/$hash && `stat -c%s $binstore/$hash` != `stat -c%s $src` ]]; then
             echo "git-bin-add: SIGNATURE CONFLICT in $src!"
-            echo "git-bin-add: $src  in store has size `stat -c%s $BINSTORE/$hash`, and your file has size `stat -c%s $src`"
+            echo "git-bin-add: $src  in store has size `stat -c%s $binstore/$hash`, and your file has size `stat -c%s $src`"
             return
-        elif [[ -e $BINSTORE/$hash && `stat -c%s $BINSTORE/$hash` == `stat -c%s $src` ]]; then
+        elif [[ -e $binstore/$hash && `stat -c%s $binstore/$hash` == `stat -c%s $src` ]]; then
             echo "git-bin-add: duplicate file $src, pointing at existing binstore copy."
             #TODO: symlink it anyways. There might be multiple 'copies' of the same file in a git repo.
             # drop the src file, symlink to the binstore:
             cp -f $src .tmp_$hash
-            (rm -f $src && ln -s $BINSTORE/$hash $src && git add $src && rm -f .tmp_$hash) || (echo "git-bin-add: something went wrong when adding $src, reverting" && mv -f .tmp_$hash $src)
+            (rm -f $src && ln -s $binstore/$hash $src && git add $src && rm -f .tmp_$hash) || (echo "git-bin-add: something went wrong when adding $src, reverting" && mv -f .tmp_$hash $src)
             continue
         fi
 
         # BACKUP
         cp -f $src .tmp_$hash
 
-        (cp -f $src $BINSTORE/$hash && rm -f $src && ln -s $BINSTORE/$hash $src && git add $src && rm -f .tmp_$hash) || (echo "git-bin-add: something went wrong when adding $src, reverting" && mv -f .tmp_$hash $src)
+        (cp -f $src $binstore/$hash && rm -f $src && ln -s $binstore/$hash $src && git add $src && rm -f .tmp_$hash) || (echo "git-bin-add: something went wrong when adding $src, reverting" && mv -f .tmp_$hash $src)
     done
 }
 
 function editbin {
-    if [[ ! -d $BINSTORE ]];
+    if [[ ! -d $binstore ]];
     then
-        echo "git-bin-edit: the binstore ($BINSTORE) doesn't exist. You probably haven't added any binaries to git-bin yet."
+        echo "git-bin-edit: the binstore ($binstore) doesn't exist. You probably haven't added any binaries to git-bin yet."
         return
     fi
 
-    while [[ "x$1" != "x" ]];
+    while [[ ! -z "$1" ]];
     do
         src=$1 ; shift
         if [[ -d $src ]]; 
@@ -59,7 +67,7 @@ function editbin {
             continue
         fi
         storefile=`readlink $src`
-        [[ $? == 1 || "$(dirname $storefile)" != "$BINSTORE" ]] && continue #not a symlink
+        [[ $? == 1 || "$(dirname $storefile)" != "$binstore" ]] && continue #not a symlink
         tmpfile=.tmp_$(basename $storefile)
 
         cp $storefile $tmpfile && mv -f $tmpfile $src && echo "git-bin-edit: $src is now available for editing"
@@ -67,13 +75,13 @@ function editbin {
 }
 
 function resetbin {
-    if [[ ! -d $BINSTORE ]];
+    if [[ ! -d $binstore ]];
     then
-        echo "git-bin-reset: the binstore ($BINSTORE) doesn't exist. You probably haven't added any binaries to git-bin yet."
+        echo "git-bin-reset: the binstore ($binstore) doesn't exist. You probably haven't added any binaries to git-bin yet."
         return
     fi
 
-    while [[ "x$1" != "x" ]];
+    while [[ ! -z "$1" ]];
     do
         src="$1" ; shift
         if [[ -d $src ]]; 
@@ -91,7 +99,7 @@ function resetbin {
                 # the file will be a symlink to it's contents.
 
                 # check whether the file is already a symlink to its hash in the binstore
-                [[ -L $src && "`readlink $src`" == "$BINSTORE/$hash" ]] || (echo "git-bin-reset: something is horribly wrong with $src. It should be a symlink to it's contents, but isn't" && return)
+                [[ -L $src && "`readlink $src`" == "$binstore/$hash" ]] || (echo "git-bin-reset: something is horribly wrong with $src. It should be a symlink to it's contents, but isn't" && return)
 
                 symtarget=`readlink $src`
                 echo "git-bin-reset: unstaging $src"
@@ -102,9 +110,9 @@ function resetbin {
                 # the file is not a symlink to it's contents.
                 # check whether the file is already a symlink to its hash in the binstore
                 # i.e. there is nothing to reset
-                [[ -L $src && "`readlink $src`" == "$BINSTORE/$hash" ]] && continue 
+                [[ -L $src && "`readlink $src`" == "$binstore/$hash" ]] && continue 
 
-                if [[ ! -e $BINSTORE/$hash ]];
+                if [[ ! -e $binstore/$hash ]];
                 then
                     # The hash is not in the binstore. this could be because the file was never tracked by
                     # git-bin, or because the file content has changed (following a git-bin-edit).
@@ -119,9 +127,9 @@ function resetbin {
                     cp -f $src /tmp/$src.$hash
                 else
                     # The has is in the binstore. We need to check for signature conflicts:
-                    if [[ `stat -c%s $BINSTORE/$hash` != `stat -c%s $src` ]]; then
+                    if [[ `stat -c%s $binstore/$hash` != `stat -c%s $src` ]]; then
                         echo "git-bin-reset: SIGNATURE CONFLICT in $src!"
-                        echo "git-bin-reset: $src in store has size `stat -c%s $BINSTORE/$hash`, and your file has size `stat -c%s $src`"
+                        echo "git-bin-reset: $src in store has size `stat -c%s $binstore/$hash`, and your file has size `stat -c%s $src`"
                         return
                     fi
                 fi
@@ -141,7 +149,7 @@ funcname=$1 ; shift
 
 case $funcname in
     add|edit|reset) 
-        if [[ "x$1" == "x" ]];
+        if [[ -z "$1" ]];
         then
             echo "git-bin: you must specify a file name to operate on!"
             exit 1
